### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by bumpmann** [sourcemint/sm-npm#18]
$ node --version
v0.8.11
$ npm --version
1.1.62
$ sudo npm install -g sm
npm http GET https://registry.npmjs.org/sm
npm http 304 https://registry.npmjs.org/sm
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/sourcemint-pinf-js
npm http GET https://registry.npmjs.org/sourcemint-util-js
npm http GET https://registry.npmjs.org/sourcemint-pm-sm
npm http 304 https://registry.npmjs.org/sourcemint-pm-sm
npm ERR! Error: No compatible version found: sourcemint-pm-sm@'sourcemint-pm-sm@0.1.33'
npm ERR! Valid install targets:
npm ERR! ["0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.1.16","0.1.17","0.1.18","0.1.19","0.1.20","0.1.21","0.1.22","0.1.23","0.1.24","0.1.25","0.1.26","0.1.27","0.1.28","0.1.29","0.1.30","0.1.31","0.1.32","0.1.33"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:553:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:477:15
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 2.6.38.2-grsec-xxxx-grs-ipv6-64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "sm"
npm ERR! cwd /home/bumpmann
npm ERR! node -v v0.8.11
npm ERR! npm -v 1.1.62
npm http 304 https://registry.npmjs.org/sourcemint-pinf-js
npm http 304 https://registry.npmjs.org/sourcemint-util-js
npm http 304 https://registry.npmjs.org/semver
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bumpmann/npm-debug.log
npm ERR! not ok code 0

**Comment by bumpmann** [comment]
Okay, working with newest npm.

$ sudo npm install -g npm
...
$ npm --version
1.2.18
