### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by cadorn** [sourcemint/sm-npm#6]

**Comment by japj** [comment]
Hi, I just ran into the following on Windows:

```
npm install -g sm

....

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<EventEmitter> has no method 'getuid'
    at Object.<anonymous> (C:\Dropbox\dev\bin\node_modules\sm\scripts\postinstall.js:10:59)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

npm ERR! sm@0.1.76 postinstall: `node ./scripts/postinstall.js`
npm ERR! `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
npm ERR!
...
npm ERR! node -v v0.6.17
npm ERR! npm -v 1.1.21
npm ERR! code ELIFECYCLE
npm ERR! message sm@0.1.76 postinstall: `node ./scripts/postinstall.js`
npm ERR! message `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
npm ERR! errno {}
npm ERR!
```

**Comment by cadorn** [comment]
@japj FYI, This issue will remain open until windows support is complete.

The `getuid` issue is the first one that comes up at this time. There are more.

If anyone is interested in helping with windows support, please express your interest here and we can get a team going to bring and maintain windows support for sourcemint.

**Comment by japj** [comment]
I'm up for working on Windows support (if only to get cloud9 running there 'out of the box').

Do you have an idea or list of the things you expect that need to be done?

**Comment by cadorn** [comment]
@japj If it is for cloud9 we don't need to get `sm` running on windows. See: https://github.com/ajaxorg/cloud9/issues/1407

**Comment by japj** [comment]
@cadorn what about people that want to contribute to cloud9 on windows?
and it might be a good 'testcase' to get working?

**Comment by cadorn** [comment]
@japj Right. Feel free to jump on http://groups.google.com/group/sourcemint to start a thread. We can discuss the various things that may be involved and where to start.

**Comment by gero3** [comment]
Actually I'm also willing to help with it.
I have figured out several things but the most important one right now is where we will allocate the .sourcemint directory. I have a PR open that suggests APPDATA in windows.

**Comment by cadorn** [comment]
I will let you take the lead on making these decisions to get things running. We can discuss the details when I merge back.

If I may; let's discuss on the mailing list and keep this ticket for progress updates that others can test.
